/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as UpdateScriptJson } from "../scripts/Update.ral.json";
import { default as WithdrawScriptJson } from "../scripts/Withdraw.ral.json";

export const Update = new ExecutableScript<{
  token: HexString;
  newMerkleRoot: HexString;
}>(Script.fromJson(UpdateScriptJson));
export const Withdraw = new ExecutableScript<{
  token: HexString;
  amount: bigint;
  proof: HexString;
  data: HexString;
}>(Script.fromJson(WithdrawScriptJson));
